//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anexo
    {
        public int IdAnexo { get; set; }
        public int IdEntrega { get; set; }
        public string NomeLogico { get; set; }
        public string CaminhoFisico { get; set; }
    
        public virtual Entrega Entrega { get; set; }
    }
}
