//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entrega
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Entrega()
        {
            this.Anexo = new HashSet<Anexo>();
        }
    
        public int IdEntrega { get; set; }
        public int IdProjeto { get; set; }
        public int IdTipoEntrega { get; set; }
        public System.DateTime DataEntrega { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Anexo> Anexo { get; set; }
        public virtual Projeto Projeto { get; set; }
        public virtual TipoEntrega TipoEntrega { get; set; }
    }
}
