//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjetoIntegradorEntities : DbContext
    {
        public ProjetoIntegradorEntities()
            : base("name=ProjetoIntegradorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aluno> Aluno { get; set; }
        public virtual DbSet<Anexo> Anexo { get; set; }
        public virtual DbSet<Curso> Curso { get; set; }
        public virtual DbSet<Entrega> Entrega { get; set; }
        public virtual DbSet<MatriculaCurso> MatriculaCurso { get; set; }
        public virtual DbSet<Papel> Papel { get; set; }
        public virtual DbSet<Pessoa> Pessoa { get; set; }
        public virtual DbSet<Projeto> Projeto { get; set; }
        public virtual DbSet<ProjetoAluno> ProjetoAluno { get; set; }
        public virtual DbSet<SituacaoProjeto> SituacaoProjeto { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TipoEntrega> TipoEntrega { get; set; }
        public virtual DbSet<TipoParticipante> TipoParticipante { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<UsuarioPapel> UsuarioPapel { get; set; }
        public virtual DbSet<vProjetoAluno> vProjetoAluno { get; set; }
    }
}
