//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioPapel
    {
        public int IdUsuario { get; set; }
        public int IdPapel { get; set; }
        public System.DateTime DataInicioVigencia { get; set; }
        public Nullable<System.DateTime> DataFimVigencia { get; set; }
    
        public virtual Papel Papel { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
