//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class vProjetoAluno
    {
        public int IdAluno { get; set; }
        public int IdProjeto { get; set; }
        public int IdTipoParticipante { get; set; }
        public System.DateTime DataRegistro { get; set; }
        public string NomeAluno { get; set; }
        public string TipoParticipante { get; set; }
    }
}
